### ISSUE TITLE
Allow for administrator to add footer with links to legal documents

### ISSUE THREAD

**Issue by neumantm** [spethso/PizzaCalculator#10]
By the EU General Data Protection Regulation, it is necessary to have a link on every public webpage, pointing to a document explaing what data is collected. Additionaly you need to link to your imprint page.

It would be nice, if the Pizza Calculator would provide a possibility for the admin to configure such links.
For example with the help of a configuration file.

**Comment by WoodNFern** [comment]
In src/data/footer.txt there can now be specified a text to be displayed as footer.
This text will be directly injected (HTML can be used).

This is not yet possible on the landing page, as footer styling appears to be significantly more difficult there.
